web_flask/forms/login.py
#!/usr/bin/python3
"""Login form extended from flask wtf"""
from flask_wtf import FlaskForm
from wtforms import (StringField, PasswordField, SubmitField)
from wtforms.validators import InputRequired, Length


class LoginForm(FlaskForm):
    """Class extended from flask wtf for form login"""
    email = StringField('Username', validators=[InputRequired(),
                                             Length(min=1, max=100)])
    password = PasswordField('Password', validators=[InputRequired(),
                                             Length(min=1, max=100)])
    submit = SubmitField('Login')

web_flask/routes/application.py
from flask import Blueprint, render_template, redirect, url_for, flash
from ..forms.application import ApplicationForm
from models.user import User
from models.job import Job
from models.application import Application
from flask_login import login_required, current_user
from models import storage
from flask_mail import Message

applications = Blueprint('applications', __name__)

@applications.route('/apply/<string:job_id>', methods=['GET', 'POST'], strict_slashes=False)
@login_required
def apply(job_id):
    """Handles job apllication"""
    from web_flask import mail
    if not current_user.email_verify:
        return redirect(url_for('user.confirm_page'))
    form = ApplicationForm()
    if form.validate_on_submit():
        # Create a new application
        data = {
            "user_id": current_user.id,
            "job_id": job_id,
            "cover_letter": form.cover_letter.data
        }
        for item in current_user.applications:
            if item.job_id == job_id:
                flash('You already applied for this job')
                return render_template('apply.html', job_id=job_id, form=form)
        new_application = Application(**data)
        # Save the application to the database
        new_application.save()
        flash('Application submitted successfully!')
        job = storage.get(Job, job_id)
        employer = storage.get(User, job.user_id)
        msg = Message('New Job Application Notification',
                        sender='noreply',
                        recipients=[employer.email])
        msg. body = f'Hi,\n\nYou have a new job application for the position of {job.title}.\n\nApplicant: {current_user.username}\n\nPlease log in to your job portal to review the application.'
        mail.send(msg)
        return redirect(url_for('job.home'))
    return render_template('apply.html', job_id=job_id, form=form)


@applications.route('/applications/<string:job_id>', methods=['GET', 'POST'], strict_slashes=False)
@login_required
def get_applications(job_id):
    """Handles get for all job apllication"""
    apps_data = []
    apps = storage.all(Application).values()
    for app in apps:
        if app.job_id == job_id:
            job = storage.get(Job, app.job_id)
            user = storage.get(User, app.user_id)
            app.title = job.title
            app.firstname = user.first_name
            app.lastname = user.last_name
            apps_data.append(app)
    return render_template('application-list.html', applications=apps_data)


@applications.route('/application/<string:app_id>', methods=['GET'], strict_slashes=False)
@login_required
def single_app(app_id):
    """Single App route - displays a single app"""
    app = storage.get(Application, app_id)
    if app:
        user = storage.get(User, app.user_id)
        job = storage.get(Job, app.job_id)
        return render_template('singleapp.html', job=job, user=user, app=app)
    else:
        return render_template('404.html')
    
@applications.route('/application/<string:app_id>', methods=['POST'], strict_slashes=False)
def delete_app(app_id):
    """Delete App route - delete a application"""
    if not current_user.email_verify:
        return redirect(url_for('user.confirm_page'))
    app = storage.get(Application, app_id)
    if app:
       storage.delete(app)
       storage.save()
       flash('Application deleted successfully!')
       return redirect(url_for('job.home'))
    else:
        return render_template('404.html')

web_flask/routes/job.py
#!/usr/bin/env python3
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_required, current_user
from ..forms.post_job import PostJobForm
from models.job import Job
from models.user import User
from models import storage


job = Blueprint('job', __name__)


@job.route('/', methods=['GET'], strict_slashes=False)
def home():
    """home route"""
    jobs_data = []
    jobs = storage.all(Job).values()
    for index, job in enumerate(jobs):
        # Limit the loop to the first 9 iterations
        if index >= 7:
            break
        user = storage.get(User, job.user_id)
        if user:
            job_data = {
                'id': job.id,
                'title': job.title,
                'description': job.description,
                'created_at': job.created_at,
                'username': user.username,
                'user_id': job.user_id
            }
        jobs_data.append(job_data)
    return render_template('home.html', cards=jobs_data)


@job.route('/jobs', methods=['GET', 'POST'], strict_slashes=False)
def all_jobs():
    """List all jobs"""
    jobs_data = []
    keyword = request.args.get('search', '')
    if not keyword:
        jobs = storage.all(Job).values()
    else:
        jobs = storage.search(Job, keyword).values()
    for job in jobs:
        user = storage.get(User, job.user_id)
        # extract data from form and add user_id
        if user:
            job_data = {
                'id': job.id,
                'title': job.title,
                'description': job.description,
                'location': job.location,
                'salary': job.salary,
                'requirements': job.requirements,
                'deadline': job.deadline,
                'created_at': job.created_at,
                'username': user.username,
                'user_id': job.user_id
            }
        jobs_data.append(job_data)
    return render_template('jobs.html', cards=jobs_data, search=keyword)


@job.route('/job/create', methods=['POST', 'GET'])
@login_required
def post_job():
    """Post job route"""
    if not current_user.email_verify:
        flash('Please verify your email to continue!')
        return redirect(url_for('user.confirm_page'))
    form = PostJobForm()
    if form.validate_on_submit():
        """Handle form submission logic here"""
        data = {
            "title": form.title.data,
            "description": form.description.data,
            "location": form.location.data,
            "salary": form.salary.data,
            "requirements": form.requirements.data,
            "deadline": form.deadline.data,
            "type": form.type.data,
            "user_id": current_user.id
        }
        # Create new User
        new_job = Job(**data)
        # Save User in database
        new_job.save()
        flash("Job posted successfully")
        # Rediect to Login Page
        return redirect(url_for('job.home'))
    flash("Fill in all fields")
    return render_template('postform.html', form=form)


@job.route('/job/<string:job_id>', methods=['GET'], strict_slashes=False)
def single_job(job_id):
    """Single Job route - displays a single job"""
    job = storage.get(Job, job_id)
    if job:
        user = storage.get(User, job.user_id)
        return render_template('singlejob.html', job=job, user=user)
    else:
        return render_template('404.html')


@job.route('/job/<string:job_id>', methods=['POST'], strict_slashes=False)
def delete_job(job_id):
    """Delete Job route - delete a single job"""
    if not current_user.email_verify:
        flash('Please verify your email to continue!')
        return redirect(url_for('user.confirm_page'))
    job = storage.get(Job, job_id)
    if job:
       storage.delete(job)
       storage.save()
       flash('Job deleted successfully!')
       return redirect(url_for('job.home'))
    else:
        return render_template('404.html')

web_flask/routes/user.py
#!/usr/bin/env python3
"""User routes"""
from flask import Blueprint, render_template, redirect, url_for, flash
from ..forms.login import LoginForm
from ..forms.register import RegisterForm, UpdateForm
from flask_bcrypt import Bcrypt
from models.user import User
from models.job import Job
from models import storage
from flask_login import login_user, current_user, login_required, logout_user
from itsdangerous import URLSafeTimedSerializer
import os
from dotenv import load_dotenv
from flask_mail import Message

load_dotenv()


# Get env variables
ITD_SECRET_KEY = os.getenv('ITD_SECRET_KEY')

bcrypt = Bcrypt()
user = Blueprint('user', __name__)
serializer = URLSafeTimedSerializer(ITD_SECRET_KEY)

@user.route('/login', methods=['GET', 'POST'], endpoint='login')
def login():
    """Login route"""
    if current_user.is_authenticated:
        return redirect(url_for('job.home'))
    form = LoginForm()
    if form.validate_on_submit():
        # Handle form submission logic here
        email = form.email.data
        password = form.password.data
        user = storage.get_email(User, email.lower())
        if user and bcrypt.check_password_hash(user.password, password):
            login_user(user)
            flash('Logged in successfully')
            return redirect(url_for('job.home'))
        flash('Invalid username or password')
    return render_template('login.html', form=form)


@user.route('/register', methods=['GET', 'POST'], endpoint='register')
def register():
    """Register route"""
    if current_user.is_authenticated:
        return redirect(url_for('job.home'))
    form = RegisterForm()
    if form.validate_on_submit():
        """Handle form submission logic here"""
        # extract data from form
        data = {
            "username": form.username.data,
            "first_name": form.firstname.data,
            "last_name": form.lastname.data,
            "password": bcrypt.generate_password_hash(form.password.data).decode('utf-8'),
            "email": form.email.data.lower(),
            "role": form.role.data,
            "portfolio_url": form.portfolio_url.data,
            "github_url": form.github_url.data,
            "email_verify": False
        }
        # Check if the email is already registered
        existing_email = storage.get_email(User, data['email'])
        if existing_email:
            flash('Email address is already registered. Please use a different email.')
            return redirect(url_for('user.register'))
        # Check if the username already exist
        existing_username = storage.get_username(User, data['username'])
        if existing_username:
            flash('Username is already registered. Please use a different username.')
            return redirect(url_for('user.register'))
        # Create new User
        new_user = User(**data)
        # Save User in database
        new_user.save()
        flash("User Created Successfully")
        # Login user
        login_user(new_user)
        # Redirect to confirm email
        return render_template('confirm-email.html')
    for field, errors in form.errors.items():
        for error in errors:
            flash(f"{form[field].label.text}: {error}")
    return render_template('register.html', form=form,)


@user.route('/confirm_email', methods=['GET', 'POST'], endpoint='confirm_email')
def confirm_email():
    """Sends link to verify email"""
    from web_flask import mail
    if current_user.email_verify:
        return redirect(url_for('job.home'))
    user_id = current_user.id 
    user_email = current_user.email
    token = serializer.dumps(user_id)
    verification_link = url_for('user.verify_email', token=token, _external=True)
    msg = Message('Verify Your Email',
                  sender='noreply',
                  recipients=[user_email])
    msg.body = f'To Complete your sign up please click the following link to verify your email: {verification_link}'
    mail.send(msg)
    flash('Please check your email for confirmation link')
    return render_template('confirm-email.html')

@user.route('/confirm-page', methods=['GET'], endpoint='confirm_page')
def confirm_page():
    """renders confirm email page"""
    if current_user.email_verify:
        return redirect(url_for('job.home'))
    return render_template('confirm-email.html')

@user.route('/verify_email/<token>', methods=['GET', 'POST'], endpoint='verify_email')
def verify_email(token):
    """Handles email verification"""
    try:
        user_id = serializer.loads(token, max_age=900)
        user = user = storage.get(User, user_id)
        user.email_verify = True
        user.save()
        flash('Email verification successful')
        return redirect(url_for('job.home'))
    except Exception as e:
        # Handle token verification failure
        flash('Email verification failed. Please try again')
        return redirect(url_for('user.confirm_email'))


@user.route("/logout")
@login_required
def logout():
    """Log out functionality"""
    logout_user()
    flash('User logged out successfully')
    return redirect(url_for('user.login'))

@user.route("/user/<string:user_id>")
@login_required
def single_user(user_id):
    """Return a single user"""
    user = storage.get(User, user_id)
    if user:
       if user.role == "Employer":
        for job in user.jobs:
            job.username = user.username
        return render_template('profile.html', user=user, jobs=user.jobs)
       else:
            for app in user.applications:
                job = storage.get(Job, app.job_id)
                user = storage.get(User, app.user_id)
                app.title = job.title
                app.firstname = user.first_name
                app.lastname = user.last_name
            return render_template('profile.html', user=user, applications=user.applications)
    else:
        return render_template('404.html')
    
@user.route('/user/<string:user_id>', methods=['POST'], strict_slashes=False)
@login_required
def delete_user(user_id):
    """Delete User route - delete a user account"""
    user = storage.get(User, user_id)
    if user:
        storage.delete(user)
        storage.save()
        return redirect(url_for('user.register'))
    else:
        return render_template('404.html')
    

# @user.route('/user/update/<string:user_id>', methods=['GET', 'POST'])
# @login_required
# def update_user(user_id):
#     """Update route"""
#     user = storage.get(User, user_id)
#     if not user:
#         flash("User not found", "error")
#         return redirect(url_for('job.home'))
#     form = UpdateForm(obj=user)
#     if form.validate_on_submit():
#         """Handle form submission logic here"""
#         # extract data from form
#         data = {
#             "first_name": form.firstname.data,
#             "last_name": form.lastname.data,
#             "password": bcrypt.generate_password_hash(form.password.data).decode('utf-8'),
#             "portfolio_url": form.portfolio_url.data,
#             "github_url": form.github_url.data
#         }
#         # Create new User
#         user.update(**data)
#         flash("User Updated Successfully", "success")
#         # Rediect to Loggin Page
#         return redirect(url_for('job.home'))
#     return render_template('update_user.html', form=form, user=current_user)
    
@user.route('/update_user/', methods=['GET', 'POST'])
@login_required
def update_user():
    """Update route"""
    user = storage.get(User, current_user.id)
    if not user:
        flash("User not found", "error")
        return render_template('404.html')
    form = UpdateForm(obj=user)
    if form.validate_on_submit():
        """Handle form submission logic here"""
        # extract data from form
        data = {
            "first_name": form.first_name.data if form.first_name.data else user.first_name,
            "last_name": form.last_name.data if form.last_name.data else user.last_name,
            "password": bcrypt.generate_password_hash(form.new_password.data).decode('utf-8') if form.new_password.data else user.password,
            "portfolio_url": form.portfolio_url.data if form.portfolio_url.data else user.portfolio_url,
            "github_url": form.github_url.data if form.github_url.data else user.github_url,
            # "email_verify": user.email_verify,
            # "username": user.username,
            # "role": user.role,
            # "email": user.email
        }
        # Create new User
        user.update(**data)
        # flash("User Updated Successfully")
        # return redirect(url_for('job.home'))
        if current_user.role == "Employer":
            for job in current_user.jobs:
                job.username = current_user.username
                flash("User current Successfully")
                return render_template('profile.html', user=current_user, jobs=current_user.jobs)
        else:
            for app in current_user.applications:
                job = storage.get(Job, app.job_id)
                user = storage.get(User, app.user_id)
                app.title = job.title
                app.firstname = user.first_name
                app.lastname = user.last_name
            return render_template('profile.html', user=user, applications=user.applications)
    return render_template('updateuser.html', form=form)

web_flask/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="../static/image/icon.ico" >
    <link rel="stylesheet" href="../static/css/main.css">
    <link rel="stylesheet" href="../static/css/base.css">
    {% block styles %}{% endblock %}
    <title>{% block title %}JobCircus - Welcome{% endblock %}</title>
</head>
<body>
    <header>
        <nav>
            <div class="brand">
                <a href="{{ url_for('job.home') }}"><div class="logo"><span>JC</span>JOBCIRCUS</div></a>
            </div>
            <div class="user-section">
                {% if current_user.is_authenticated %}
                <div class="user-name">
                    <a href="{{ url_for('user.single_user', user_id=current_user.id) }}"><div class="user-img"><span>{{ current_user.username[0].capitalize() }}</span>{{ current_user.username.capitalize() }}</div></a>
                </div>
                <div class="login-logout">
                    <a href="{{ url_for('user.logout') }}">Logout</a>
                </div>
                {% else %}
                <div class="user-name">
                    <a href="{{ url_for('user.login') }}">Login</a>
                </div>
                <div class="login-logout">
                    <a href="{{ url_for('user.register') }}">Get Started</a>
                </div>
                {% endif %}
                
            </div>
        </nav>
    </header>
    <main>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
        <div class="flash-message">
            <p class="{{ category }}">{{ messages[0] }}</p>
            <button type="button" data-dismiss="alert" aria-label="close" onclick="closeAlert(this)"><span aria-hidden="true">&times;</span></button>
        </div>
    {% endif %}
    {% endwith %}
    {% block content %}{% endblock %}
    </main>
    <footer>
        <span>Copyright&copy;2023 JobCircus. All rights reserved.</span>
    </footer>

    <script>
        function closeAlert(button) {
            // Find the parent element (the alert box) and remove it
            const alertBox = button.parentElement;
            alertBox.style.display = 'none';
        }
    </script>
</body>
</html>

web_flask/templates/card.html
{% block styles %}
    <!-- Link specific CSS styles for the card page -->
    <link rel="stylesheet" href="../static/css/card.css">
    {% endblock %}
<div class="job-card">
    <div class="card-header">
        <p>{{ card.username[0:2].upper() }}</p>
        <span>{{ card.created_at.strftime("%B %d") }}</span>
    </div>
    <div class="card-body">
        <h3 class="card-title">{{ card.title }}</h3>
        <p class="card-description">{{ card.description[:100] + '...' }}</p>
    </div>
    <div class="card-view-buttons">
        <a href="{{ url_for('job.single_job', job_id=card.id) }}" class="view-btn">Details</a>
        {% if current_user and current_user.role != 'Employer' %}
        <a href="{{ url_for('applications.apply', job_id=card.id) }}" class="apply-btn">Apply</a>
        {% endif %}
    </div>
    {% if current_user and current_user.id == card.user_id %}
    <div class="card-delete-btn"> 
        <button class="edit-btn">Update</button>
        <form method="POST" action="{{ url_for('job.delete_job', job_id=card.id) }}" onsubmit="return confirm('Are you sure you want to delete this job?');">
            <input type="hidden" name="_method" value="DELETE">
            <button type="submit" class="delete-btn">Delete</button>
        </form>
    </div>
    <p class="view-applicants"><a href="{{ url_for('applications.get_applications', job_id=card.id) }}">View Applicants</a></p>
    {% endif %}
</div>

web_flask/templates/home.html
{% extends "base.html" %}
{% block styles %}
    <!-- Link specific CSS styles for the login page -->
    <link rel="stylesheet" href="../static/css/home.css">
{% endblock %}
{% block title %}JobCircus - Home{% endblock %}
{% block content %}
    <div class="home-container">
        <div class="hero-section">
            <div class="hero-right">
                <h2>GET THE <br>RIGHT JOB<br> YOU <span>DESERVE</span></h2>
                <form method="get" action="{{ url_for('job.all_jobs') }}">
                    <input type="text" id="search" name="search" placeholder="Search Job" value="{{ search }}">
                    <input type="submit" value="Search" class="search-submit">
                </form>
            </div>
            <div class="hero-left">
                <img src="../static/image/hero image.jpg" alt="hero-image">
            </div>
        </div>
        <div class="post-hero-section">
            <p>THOUSANDS OF JOB SEEKERS GETTING JOBS DAILY</p>
        </div>
        <div class="job-type-section">
            <div class="part-time job-type">
                <div class="job-type-circle"></div>
                <h3>PARTIME JOBS</h3>
                <p>Looking for a part time job? Discover part-time roles that fit your schedule, skills and aspirations.</p>
                <a href="{{ url_for('job.all_jobs', search='partime' ) }}">View All</a>
            </div>
            <div class="fulltime job-type">
                <div class="job-type-circle"></div>
                <h3>FULLTIME JOBS</h3>
                <p>Looking for a full time job? Explore exciting opportunities that align with your skills and ambitions.</p>
                <a href="{{ url_for('job.all_jobs', search='fulltime' ) }}">View All</a>
            </div>
        </div>
        <div class="post-hero-section">
            <p></p>
        </div>
        <div class="job-listing-section">
            <h2>JOB LISTING</h2>
            <div class="job-listing">
                <!-- Include the card component -->
                {% if cards %}
                {% for card in cards %}
                {% include 'card.html' %}
                {% endfor %}
                {% else %}
                <p class="no-job">NO JOB AT THE MOMENT, PLEASE CHECK BACK LATER</p>
                {% endif %}
            </div>
            <div class="view-all-job">
                <a href="{{ url_for('job.all_jobs') }}">View All</a>
            </div>
        </div>
        <!-- Add post button  -->
        {% if current_user and current_user.role == 'Employer' %}
        <div class="add-post-home-btn">
            <a href="{{ url_for('job.post_job') }}">+</a>
        </div>
        {% endif %}
    </div>
{% endblock %}

web_flask/templates/profile.html
{% extends "base.html" %}
{% block styles %}
    <!-- Link specific CSS styles for the single job page -->
    <link rel="stylesheet" href="../static/css/profile.css">
    <!-- Link specific CSS styles for the homapage page  - this page share styling with job section of hompage - home.css  -->
    <link rel="stylesheet" href="../static/css/home.css">
{% endblock %}
{% block title %}JobCircus - Profile{% endblock %}
{% block content %}
    <div class="profile-main">
        <div class="profile">
            <div class="profile-container">
                <div class="profile-img">
                    <p class=".user-img">{{ user.username[0:2].upper() }}</p>
                </div>
                <p class="profile-username">{{ user.first_name }} {{ user.last_name }}</p>
                <p class="user-role">{{ user.role }}</p>
                <div class="profile-details">
                    <div  class="details-item">
                        <p class="details-title">USERNAME:</p>
                        <p class="details-body">{{ user.username.capitalize() }}</p>
                    </div>
                    <div  class="details-item">
                        <p class="details-title">EMAIL:</p>
                        <p class="details-body">{{ user.email.capitalize() }}</p>
                    </div>
                    <div  class="details-item">
                        <p class="details-title">GITHUB URL:</p>
                        {% if user.portfolio_url == "" %}
                        <p>Not Set</p>
                        {% else %}
                        <p>{{ user.github_url }}</p>
                        {% endif %}
                    </div>
                    <div  class="details-item">
                        <p class="details-title">PORTFOLIO URL:</p>
                        {% if user.portfolio_url == "" %}
                        <p>Not Set</p>
                        {% else %}
                        <p>{{ user.portfolio_url }}</p>
                        {% endif %}
                    </div>
                    <div class="profile-confirm-email">
                        {% if current_user.email_verify == False %}
                        <a href="{{ url_for('user.confirm_page') }}">Verify Email</a>
                        {% endif %}
                    </div>
                </div>
                {% if current_user.id == user.id %}
                    <div class="user-buttons">
                        <a href="{{ url_for('user.update_user') }}" class="user-update">Update Account</a>
                        <div class="profile-delete-btn"> 
                            <form method="POST" action="{{ url_for('user.delete_user', user_id=user.id) }}" onsubmit="return confirm('Are you sure you want to delete your account?');">
                                <input type="hidden" name="_method" value="DELETE">
                                <button type="submit" class="delete-btn">Delete Account</button>
                            </form>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
        {% if current_user.id == user.id %}
            <div class="user-jobs-app">
                {% if current_user.role == 'Job-Seeker' %}
                <!-- Include the card component -->
                <h2>Jobs Applied</h2>
                <div class="app-listing">
                    <div class="app-line"></div>
                    {% if applications %}
                        {% for app in applications %}
                        <ul>
                            <li>
                                {% include 'apply-card.html' %} 
                            </li>
                        </ul>
                        {% endfor %}
                    {% else %}
                </div>
                <p class="no-job">YOU HAVEN'T APPLIED FOR ANY JOB</p>
                {% endif %}
                {% else %}
                <div class="listing-container">
                    <div class="job-listing-section">
                        <h2>Jobs Posted</h2>
                        <div class="job-listing">
                            <!-- Include the card component -->
                            {% if jobs %}
                                {% for card in jobs %}
                                    {% include 'card.html' %}
                                {% endfor %}
                            {% else %}
                            <p class="no-job">NO JOB AT THE MOMENT, PLEASE CHECK BACK LATER</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
        {% endif %}
    </div>
{% endblock %}

web_flask/templates/protected.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
    <div class="login_container">
        <h2>Protected route</h2>
    </div>
{% endblock %}

web_flask/templates/singlejob.html
{% extends "base.html" %}
{% block styles %}
    <!-- Link specific CSS styles for the single job page -->
    <link rel="stylesheet" href="../static/css/singlejob.css">
{% endblock %}
{% block title %}JobCircus - Job{% endblock %}
{% block content %}
    <div class="singlejob">
        <div class="singlejob-container">
            <div class="singlejob-title">
                <h3>{{ job.title }}</h3>
            </div>
            <div class="singlejob-details">
                <div class="details-header">
                    {% if current_user.username == user.username %}
                    <p class="header-user">
                        <span>Posted by:</span>
                        <a href="{{ url_for('user.single_user', user_id=current_user.id) }}">You</a>
                    </p>
                    {% else %}
                    <p class="header-user"><span>Posted by:</span> 
                        <a href="{{ url_for('user.single_user', user_id=job.user_id) }}">{{ user.username }}</a>
                    </p>
                    {% endif %}
                    <p class="header-date">{{ job.created_at.strftime("%B %d") }}</p>
                </div>
                <div class="details-salary">${{ job.salary }}</div>
                <div class="details-tags">
                    <p class="details-type">{{ job.type }}</p>
                    <p class="details-location">{{ job.location }}</p>
                </div>
                <p>{{ job.description }}</p>
                <div class="details-requirement">
                    <h4 class="requirement-title">Requirements</h4>
                    <p class="requirement">{{ job.requirements }}</p>
                </div>
                <div class="button-container">
                    {% if current_user and current_user.id == job.user_id %}
                    <form method="POST" action="{{ url_for('job.delete_job', job_id=job.id) }}" onsubmit="return confirm('Are you sure you want to delete this job?');">
                        <input type="hidden" name="_method" value="DELETE">
                        <button type="submit" class="delete-btn">Delete</button>
                    </form>
                    {% elif current_user.id != job.user_id and current_user.role == 'Job-Seeker' %}
                    <a href="{{ url_for('applications.apply', job_id=job.id) }}">Apply</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}